### PR TITLE
Bumped dependency version numbers

### LINKED ISSUE #5: Update dependencies to allow latest stack LTS
Attempting to add as a dependency yields the following build errors:

```
Error: While constructing the build plan, the following exceptions were
encountered:

In the dependencies for accelerate-typelits-0.1.0.0:
    QuickCheck-2.10.1 from stack configuration does not match >=2.8 && <2.9
                      (latest matching version is 2.8.2)
    accelerate-1.1.1.0 from stack configuration does not match >=0.15 && <0.16
                       (latest matching version is 0.15.1.0)
    accelerate-random must match >=0.15 && <0.16, but the stack configuration
                      has no specified version (latest matching version
                      is 0.15.0.0)
```

### PR DESCRIPTION
**Pull request by dented42**
Rewote some functions to cope with changes in accelerate. Fixes #5.

### CODE REVIEW

**Comment by dented42** [comment]
No idea what's wrong with the CI. Good to know my talent at breaking stuff hasn't gone anywhere...

**Comment by dented42** [comment]
It builds with the latest lts using ghc-8.2.2. I'd suggest dropping the ghc-7 stack and travis config as ghc-8 seems to be pretty widely accepted at this point.

**Comment by epsilonhalbe** [comment]
hey - with the announce of ghc 8.4 - dropping 7.x is reasonable feel free to do so, note this "library" was just a way of getting my head around typelits. I believe HMatrix has an accelerate backend - with a similar api but mutch more maturity

**Comment by dented42** [comment]
Done. I'm not aware of an hmatrix accelerate backend, but I'll take a look.

**Pull request merged**
